### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by brostosjoined** [CrossJoy/Bombsquad-Modding#4]
Happens when click the practice tools window on a server 

```python
Exception in Python call:
  root call: <ba.Call object; _call=<function doTestButton at 0x0F52C758> _args=(<advanced_party_window.ModifiedPartyWindow object at 0x03BC0E10>,) _keywds={}>
  root call origin: practice_tools.py:146
  context_ref: empty
Traceback (most recent call last):
  File "C:\Users\rover\Desktop\games\BombSquad_Windows_1.7.24\ba_data\python\babase\_general.py", line 262, in __call__
    return self._call(*self._args + args_extra, **self._keywds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rover\AppData\Local\BombSquad\mods\practice_tools.py", line 531, in doTestButton
    bs.Call(PracticeWindow())
            ^^^^^^^^^^^^^^^^
  File "C:\Users\rover\AppData\Local\BombSquad\mods\practice_tools.py", line 1691, in __init__
    self._tabs[tab_id] = tabtype(self)
                         ^^^^^^^^^^^^^
  File "C:\Users\rover\AppData\Local\BombSquad\mods\practice_tools.py", line 749, in __init__
    with activity.context:
         ^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'context'
Exception ignored in: <function PracticeWindow.__del__ at 0x0F5375C8>
Traceback (most recent call last):
  File "C:\Users\rover\AppData\Local\BombSquad\mods\practice_tools.py", line 1582, in __del__
    self.activity.globalsnode.paused = False
    ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'globalsnode'
```

**Comment by CrossJoy** [comment]
Resolved on newer version
